# coding: utf-8

# flake8: noqa

"""
    WaterProbe API

    API for waterprobing  # noqa: E501

    The version of the OpenAPI document: 1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

__version__ = "1.0.0"

# import apis into sdk package
from openapi_client.api.datastream_api import DatastreamApi
from openapi_client.api.feature_of_interest_api import FeatureOfInterestApi
from openapi_client.api.location_api import LocationApi
from openapi_client.api.observation_api import ObservationApi
from openapi_client.api.observed_property_api import ObservedPropertyApi
from openapi_client.api.sensor_api import SensorApi
from openapi_client.api.thing_api import ThingApi

# import ApiClient
from openapi_client.api_client import ApiClient
from openapi_client.configuration import Configuration
from openapi_client.exceptions import OpenApiException
from openapi_client.exceptions import ApiTypeError
from openapi_client.exceptions import ApiValueError
from openapi_client.exceptions import ApiKeyError
from openapi_client.exceptions import ApiException
# import models into sdk package
from openapi_client.models.data_stream import DataStream
from openapi_client.models.feature_of_interest import FeatureOfInterest
from openapi_client.models.inline_response201 import InlineResponse201
from openapi_client.models.location import Location
from openapi_client.models.observation import Observation
from openapi_client.models.observed_property import ObservedProperty
from openapi_client.models.sensor import Sensor
from openapi_client.models.thing import Thing
from openapi_client.models.tm_instant import TmInstant
from openapi_client.models.tm_object import TmObject

