version: '3.1'

services:
        mongo:
                build:
                  context: .
                  dockerfile: Dockerfile-custommongo
                image: sw708e19/mongo:latest
                restart: always
                ports: 
                  - 27017:27017
                networks:
                  - mynet
        sensor_things_api:
                build:
                  context: ./SensorThingsAPI/src/Org.OpenAPITools/
                  dockerfile: Dockerfile_sensor_things_api
                image: sw708e19/sensor_things_api:latest
                restart: always
                ports:
                  - 51099:80
                environment:
                  MongoDB__Host: mongo
                depends_on:
                  - mongo
                networks:
                  - mynet


networks:
        mynet:
