# coding: utf-8

"""
    WaterProbe API

    API for waterprobing  # noqa: E501

    The version of the OpenAPI document: 1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.observed_property_api import ObservedPropertyApi  # noqa: E501
from openapi_client.rest import ApiException


class TestObservedPropertyApi(unittest.TestCase):
    """ObservedPropertyApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.observed_property_api.ObservedPropertyApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_observed_property(self):
        """Test case for delete_observed_property

        Deletes an ObservedProperty  # noqa: E501
        """
        pass

    def test_get_observed_property(self):
        """Test case for get_observed_property

        gets an ObservedProperty  # noqa: E501
        """
        pass

    def test_post_observed_property(self):
        """Test case for post_observed_property

        Creates a new ObservedProperty  # noqa: E501
        """
        pass

    def test_put_observed_property(self):
        """Test case for put_observed_property

        updates an ObservedProperty  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
