# coding: utf-8

# flake8: noqa
"""
    WaterProbe API

    API for waterprobing  # noqa: E501

    The version of the OpenAPI document: 1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

# import models into model package
from openapi_client.models.data_stream import DataStream
from openapi_client.models.feature_of_interest import FeatureOfInterest
from openapi_client.models.inline_response201 import InlineResponse201
from openapi_client.models.location import Location
from openapi_client.models.observation import Observation
from openapi_client.models.observed_property import ObservedProperty
from openapi_client.models.sensor import Sensor
from openapi_client.models.thing import Thing
from openapi_client.models.tm_instant import TmInstant
from openapi_client.models.tm_object import TmObject
