FROM nginx

# Nginx will listen on this port
EXPOSE 80

# Remove the default config file
RUN rm /etc/nginx/conf.d/default.conf

# Copy new nginx configuration file
COPY ./code/app.conf /etc/nginx/conf.d/
