FROM nginx

# Nginx will listen on this port
EXPOSE 80

# Remove the default config file that
# /etc/nginx/nginx.conf includes
RUN rm /etc/nginx/conf.d/default.conf

# We copy our nginx configuration file,
# so nginx will use that instead.
COPY ./code/app.conf /etc/nginx/conf.d/
