# Dockerfile-flask
# We simply inherit the Python 3 image. This image does
# not particularly care what OS runs underneath

FROM python:3.6

# Set an environment variable with the directory
# where we'll be running the app

ENV APP /app
# Create the directory and instruct Docker to operate
# from there from now on

RUN mkdir $APP
WORKDIR $APP

# Expose the port uWSGI will listen on

EXPOSE 5000

# Copy the requirements file in order to install
# Python dependencies

COPY requirements.txt .

# Install Python dependencies

RUN pip install -r requirements.txt

# We copy the rest of the codebase into the image
COPY ./client .

# Copy the code into the client
COPY ./code ./client

#install the client
RUN python3 setup.py install --user

#Our application is now located here.
#Note: synes generelt disse directories er sjove
#synes fx at app.init burde være i client/code og ikke bare i
#client og at setup.py burde være i ./client, men det er i .
WORKDIR ./client


#RUN pip install setuptools==3.0

# Finally, we run uWSGI with the ini file we
# created earlier

CMD [ "uwsgi", "--ini", "app.ini" ]
