version: '3.1'

services:
  mongo:
    build:
      context: .
      dockerfile: Dockerfile-custommongo
    restart: always
    ports:
      - 27017:27017


  sigfoxapi:
    build:
      context: ..
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:80
    environment:
      MongoDB__Host: mongo
    depends_on:
      - mongo
