#Tutorial used https://idratherbewriting.com/learnapidoc/pubapis_openapi_step1_openapi_object.html
openapi: "3.0.2"
info:
  title: "WaterProbe API"
  description: "API for waterprobing"
  version: "1"

paths:
  /Thing:
    get:
      tags: 
      - Thing
      summary: "Get an existing probe"
      operationId: getThing
      parameters:
       - $ref: '#/components/parameters/thingname'
      responses:
        200:
          $ref: '#/components/responses/200'
        404:
          $ref: '#/components/responses/404'
    post:
      tags:
       - Thing
      summary: "Creates a new probe"
      description: "Creates new thing"
      operationId: "NewThing"
      security:
        - oauth2:
          - modifyData
      responses:
        201:
          $ref: '#/components/responses/201'
        404:
          $ref: '#/components/responses/404'
      requestBody:
        description: Optional properties represented as json for the Thing
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/thing'
              
    delete:
      tags: 
      - Thing
      summary: "Delete an existing probe"
      operationId: deleteThing
      security:
        - oauth2:
          - modifyData
      parameters:
       - $ref: '#/components/parameters/thingname'
        
      responses:
        200:
          $ref: '#/components/responses/200'
        404:
          $ref: '#/components/responses/404'
  
  /Observation:
    get:
      tags:
      - Observation
      summary: "Call to write observation to database"
      operationId: getObservation
      responses:
        201:
          $ref: '#/components/responses/201'
        404:
          $ref: '#/components/responses/404'
      
      parameters: 
       - $ref: '#/components/parameters/observation'
    post:
      tags:
      - Observation
      summary: "Call to write observation to database"
      operationId: postObservation
      security:
        - oauth2:
          - modifyData
      responses:
        201:
          $ref: '#/components/responses/201'
        404:
          $ref: '#/components/responses/404'
      
      requestBody:
        description: Optional properties represented as json for the Thing
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/observation'
              

              
              
  /dataStream:
    get:
      tags: 
      - Datastream
      summary: "Gets a datastream"
      operationId: getDatastream
      responses:
        200:
          $ref: '#/components/responses/200'
        404:
          $ref: '#/components/responses/404'
                
      parameters: 
        - $ref: '#/components/parameters/dataStream'
        
    put:
      tags: 
      - Datastream
      summary: "put to a datastream"
      operationId: putDatastream
      security:
        - oauth2:
          - modifyData
      responses:
        201:
          $ref: '#/components/responses/201'
        404:
          $ref: '#/components/responses/404'
                
      parameters: 
        - $ref: '#/components/parameters/dataStream'
        
      requestBody:
        description: Optional properties represented as json for the dataStream
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/dataStream'
    
    post:
      tags: 
      - Datastream
      summary: "posts a datastream"
      operationId: postDatastream
      security:
        - oauth2:
          - modifyData
      responses:
        201:
          $ref: '#/components/responses/201'
        404:
          $ref: '#/components/responses/404'
                
      requestBody:
        description: Optional properties represented as json for the dataStream
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/dataStream'
    
    delete:
      tags: 
      - Datastream
      summary: "deletes a datastream"
      operationId: deleteDatastream
      security:
        - oauth2:
          - modifyData
      responses:
        200:
          $ref: '#/components/responses/200'
        404:
          $ref: '#/components/responses/404'
                
      parameters: 
        - $ref: '#/components/parameters/dataStream'
    
    
  /sensor:
    get:
      tags: 
      - Sensor
      summary: "gets a sensor"
      operationId: getSensor
      responses:
        200:
          $ref: '#/components/responses/200'
        404:
         $ref: '#/components/responses/404'
                
      parameters: 
        - $ref: '#/components/parameters/sensor'
        
    
    put:
      tags: 
      - Sensor
      summary: "puts a sensor"
      operationId: putSensor
      security:
        - oauth2:
          - modifyData
      responses:
        200:
          $ref: '#/components/responses/200'
        404:
          $ref: '#/components/responses/404'
                
      parameters: 
        - $ref: '#/components/parameters/sensor'
      
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/sensor'
        
    post:
      tags: 
      - Sensor
      summary: "post a sensor"
      operationId: postSensor
      security:
        - oauth2:
          - modifyData
      responses:
        200:
          $ref: '#/components/responses/200'
        404:
          $ref: '#/components/responses/404'
                
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/sensor'
        
    
    delete:
      tags: 
      - Sensor
      summary: "deletes a sensor"
      operationId: deleteSensor
      security:
        - oauth2:
          - modifyData
      responses:
        200:
          $ref: '#/components/responses/200'
        404:
          $ref: '#/components/responses/404'
      parameters: 
        - $ref: '#/components/parameters/sensor'
    
      
  /Location:
    get:
      tags:
       - Location
      summary: "gets a location"
      operationId: getLocation
      responses:
        200:
          $ref: '#/components/responses/200'
        404:
          $ref: '#/components/responses/404'
      parameters:
      - $ref: '#/components/parameters/location'
    put:
      tags:
      - Location
      summary: "updates a location"
      operationId: putLocation
      security:
        - oauth2:
          - modifyData
      responses:
        200:
          $ref: '#/components/responses/200'
        404:
          $ref: '#/components/responses/404'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/location'
        
        
    post:
      tags:
       - Location
      summary: "posting a new location"
      operationId: postlocation
      security:
        - oauth2:
          - modifyData
      responses:
        201:
          $ref: '#/components/responses/201'
        404:
          $ref: '#/components/responses/404'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/location'
    
    delete:
      tags: 
      - Location
      summary: "deletes a sensor"
      operationId: deleteLocation
      security:
        - oauth2:
          - modifyData
      responses:
        200:
          $ref: '#/components/responses/200'
        404:
          $ref: '#/components/responses/404'
                
      parameters: 
        - $ref: '#/components/parameters/location'
        
  /FeatureOfInterest:
    get:
      tags:
       - FeatureOfInterest
      summary: "gets a FeatureOfInterest"
      operationId: getFeatureOfInterest
      responses:
        200:
          $ref: '#/components/responses/200'
        404:
          $ref: '#/components/responses/404'
      parameters:
      - $ref: '#/components/parameters/featureOfInterest'

    put:
      tags:
      - FeatureOfInterest
      summary: "updates a FeatureOfInterest"
      operationId: putFeatureOfInterest
      security:
        - oauth2:
          - modifyData
      responses:
        200:
          $ref: '#/components/responses/200'
        404:
          $ref: '#/components/responses/404'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/featureOfInterest'
        
    post:
      tags:
       - FeatureOfInterest
      summary: "posting a new FeatureOfInterest"
      operationId: postFeatureOfInterest
      security:
        - oauth2:
          - modifyData
      responses:
        201:
          $ref: '#/components/responses/201'
        404:
          $ref: '#/components/responses/404'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/featureOfInterest'
    
    delete:
      tags: 
      - FeatureOfInterest
      summary: "deletes a FeatureOfInterest"
      operationId: deleteFeatureOfInterest
      security:
        - oauth2:
          - modifyData
      responses:
        200:
          $ref: '#/components/responses/200'
        404:
          $ref: '#/components/responses/404'
                
      parameters: 
        - $ref: '#/components/parameters/featureOfInterest'
        
  /ObservedProperty:
    get:
      tags:
      - ObservedProperty
      summary: "gets an ObservedProperty"
      operationId: getObservedProperty
      responses:
        200:
          $ref: '#/components/responses/200'
        404:
          $ref: '#/components/responses/404'
      parameters:
      - $ref: '#/components/parameters/observedProperty'
    put:
      tags:
      - ObservedProperty
      summary: "updates an ObservedProperty"
      operationId: putObservedProperty
      security:
        - oauth2:
          - modifyData
      responses:
        200:
          $ref: '#/components/responses/200'
        404:
          $ref: '#/components/responses/404'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/observedProperty'
    post:
      tags:
      - ObservedProperty
      summary: "Creates a new ObservedProperty"
      operationId: postObservedProperty
      security:
        - oauth2:
          - modifyData
      responses:
        201:
          $ref: '#/components/responses/201'
        404:
          $ref: '#/components/responses/404'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/observedProperty'
    delete:
      tags:
      - ObservedProperty
      summary: "Deletes an ObservedProperty"
      operationId: deleteObservedProperty
      security:
        - oauth2:
          - modifyData
      responses:
        200:
          $ref: '#/components/responses/200'
        404:
          $ref: '#/components/responses/404'
                
      parameters: 
        - $ref: '#/components/parameters/observedProperty'


components:
  responses:
    200:
      description: Successful response
      content:
        application/json:
          schema:
            title: Sample
            type: object
            properties:
              placeholder:
                type: string
                description: Placeholder description
    201:
      description: Successful response
      content:
        application/json:
          schema:
            title: Sample
            type: object
            properties:
              placeholder:
                type: string
                description: Placeholder description
    
    404:
      description: Not created response
      content:
        text/plain:
          schema:
            title: Thing not cretead
            type: string
            example:
    
  parameters:
    observation: 
      name: observationName
      in: query
      description: "Unique observationName"
      required: false
      schema:
        type: string
      
    dataStream: 
      name: dataStreamName
      in: query
      description: "Unique dataStreamName"
      schema:
        type: string
        
    sensor: 
      name: sensorName
      in: query
      description: "Unique sensorName"
      schema:
        type: string
        
    thingname: 
      name: thingname
      in: query
      description: "Unique thingName"
      schema:
        type: string
        
    location:
      name: locationName
      in: query
      description: "Unique locationName"
      schema:
        type: string
        
    featureOfInterest:
      name: featureOfInterestName
      in: query
      description: "Unique FeatureOfInterest name"
      schema:
        type: string
        
    observedProperty: 
      name: observedPropertyName
      in: query
      description: "Unique ObservedProperty name"
      schema:
        type: string
    

  schemas:
    location:
      type: object
      required: 
        - description
        - encodingType
        - location
      properties:
        description:
          type: string 
        encodingType:
          $ref: '#/components/schemas/valueCode' 
        location:
          type: object 
            
    tmObject:
      type: object
      properties:
        time:
          type: string 
          
    
    dqElement:
      type: object
      
    
    tmInstant:
      type: object
      properties:
        time:
          type: string
          
    tmPeriod:
      type: object
      
    
    namedValue:
      type: object
      
    valueCode:
      type: object
      
  
    gm_envelope:
      type: object
  
    thing:
      type: object
      required:
        - name
        - description
        
      properties:
        name:
          type: string
        description: 
          type: string
        properties:
          type: array
          items:
            type: object
          
          
    observation:
      type: object
      required:
        - phenomenonTime 
        - resultTime
        - result
        - datastreamRef
        
      properties:
        phenomenonTime:
          $ref: '#/components/schemas/tmObject'
        resultTime:
          $ref: '#/components/schemas/tmInstant'
        result:
          type: number
        resultQuality:
          type: array
          items: 
            $ref: '#/components/schemas/dqElement'
        validTime:
          type: array
          items:
            $ref: '#/components/schemas/tmPeriod'
        parameters:
          type: array
          items:
            $ref: '#/components/schemas/namedValue'
        datastreamRef:
          type: string
        featureOfInterestRef:
          type: string
            
      
    dataStream:
      type: object
      required:
       - name
       - description
       - observationType
       - unitOfMeasurement
       - thingRef
       - sensorRef
       - observedPropertyRef
       
      properties:
        name:
          type: string
        description:
          type: string
        observationType:
          $ref: '#/components/schemas/valueCode'
        observedArea:
          $ref: '#/components/schemas/gm_envelope'
        phenomenonTime:
          $ref: '#/components/schemas/tmPeriod'
        resultTime:
          $ref: '#/components/schemas/tmPeriod'
        thingRef:
          type: string
        sensorRef:
          type: string
        observedPropertyRef:
          type: string
          
    
    sensor:
      type: object
      required:
       - name
       - description
       - encodingType
       - metaData
      
      properties:
        name:
          type: string
        description:
          type: string
        encodingType:
          $ref: '#/components/schemas/valueCode'
        metaData:
          type: object  
          
    featureOfInterest:
      type: object
      required: 
      - name
      - description 
      - encoding
      - feature
      properties:
        name:
          type: string
        description:
          type: string
        encoding:
          $ref: '#/components/schemas/valueCode'
        feature:
          type: object
    observedProperty:
      type: object
      required: 
      - name
      - definition 
      - description
      properties:
        name:
          type: string
        definition:
          type: string
        description:
          type: string
  securitySchemes:
    oAuthModify:
      type: oauth2
      description: This API uses OAuth 2 with the implicit grant flow.
      flows:
        password:
          tokenUrl: /oauth2/token
          scopes:
            modifyData: modify all data
    
