openapi: "3.0.2"
info:
  title: "Machine learning API"
  description: "API for machine learning on water probe measured data"
  version: "1"
  
  
paths:
  /probe:
    get:
      tags: 
      - Probe
      summary: "Gets all observations by a probe"
      operationId: getProbeMeasurement
      parameters:
       - $ref: '#/components/parameters/probename'
      responses:
        200:
          $ref: '#/components/responses/200'
        404:
          $ref: '#/components/responses/404'
          
  /probes:
    get:
      tags:
        - Probe
      summary: "Gets all observations by all probes"
      operationId: getProbesMeasurements
      responses:
        201:
          $ref: '#/components/responses/201'
        404:
          $ref: '#/components/responses/404'
          
    post: 
      tags:
      - Probe
      summary: "Post mahcine learning predicted values"
      description: "Creates new thing"
      operationId: "NewThing"
      security:
        - oauth2:
          - modifyData
      responses:
        201:
          $ref: '#/components/responses/201'
        404:
          $ref: '#/components/responses/404'
      requestBody:
        description: Optional properties represented as json for the Thing
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MIResult'
              
  
components:
  responses:
    200:
      description: Successful response
      content:
        application/json:
          schema:
            title: Sample
            type: object
            properties:
              placeholder:
                type: string
                description: Placeholder description
    201:
      description: Successful response
      content:
        application/json:
          schema:
            title: Sample
            type: object
            properties:
              placeholder:
                type: string
                description: Placeholder description
    
    404:
      description: Not created response
      content:
        text/plain:
          schema:
            title: Thing not cretead
            type: string
            example:
    
  parameters:
    probename: 
      name: probename
      in: query
      description: "Unique thingName"
      schema:
        type: string
        
  schemas:
    MIResult:
      type: object
        