/*
 * Backend API
 *
 * API for inserting data into db through sigfox custom callback
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using IO.Swagger.Attributes;

using Microsoft.AspNetCore.Authorization;
using IO.Swagger.Models;
using MongoDB.Driver;
using Org.OpenAPITools.Models;
using System.Linq;
using System.Text;

namespace IO.Swagger.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class DefaultApiController : ControllerBase
    {
        private const string turbidityName = "MJKDZ";
        private const string temperatureName = "DS18B20";
        private const string pHName = "PH-4502C";
        private const string nitrogenName = "Nitrogen";
        private const string phosphorusName = "Phosphorus";

        private const double measurementsPerCycle = 16;
        private const double minutesPerCycle = 15;

        private const string databaseName = "waterProbeData";
        /// <summary>
        /// Posts new data
        /// </summary>
        /// <remarks>Creates new data in db</remarks>
        /// <param name="body"></param>
        /// <response code="201">Successful response</response>
        /// <response code="404">Not created response</response>
        [HttpPost]
        [Route("/DeviceData")]
        [ValidateModelState]
        [SwaggerOperation("NewData")]
        [SwaggerResponse(statusCode: 201, type: typeof(Sample), description: "Successful response")]
        [SwaggerResponse(statusCode: 404, type: typeof(string), description: "Not created response")]
        public virtual IActionResult NewData([FromBody]DeviceData body)
        {
            try
            {
                string connectionString = "mongodb://localhost:27017";

                MongoClient client = new MongoClient(connectionString);

                var turbidityCollection = client.GetDatabase(databaseName).GetCollection<Observation>(turbidityName + "_" + body.Device);
                var temperatureCollection = client.GetDatabase(databaseName).GetCollection<Observation>(temperatureName + "_" + body.Device);
                var pHCollection = client.GetDatabase(databaseName).GetCollection<Observation>(pHName + "_" + body.Device);
                var nitrogenCollection = client.GetDatabase(databaseName).GetCollection<Observation>(nitrogenName + "_" + body.Device);
                var phosphorusCollection = client.GetDatabase(databaseName).GetCollection<Observation>(phosphorusName + "_" + body.Device);

                List<double> data = UnravelData(body.Data).Select(x => double.Parse(x)).ToList();
                List<int> timeIndices = UnravelTime(body.Data);

                DateTime startTime = DateTime.UnixEpoch.AddSeconds(int.Parse(body.Time)).Subtract(new TimeSpan(0, 15, 0));
                DateTime endTime = DateTime.UnixEpoch.AddSeconds(int.Parse(body.Time));
                string phenomenonTime = TimeToString(startTime) + "-" + TimeToString(endTime);

                Observation turbidityObservation = new Observation(phenomenonTime, TimeToString(startTime.AddMinutes(minutesPerCycle / measurementsPerCycle * timeIndices[0])), data[0]);
                Observation pHObservation = new Observation(phenomenonTime, TimeToString(startTime.AddMinutes(minutesPerCycle / measurementsPerCycle * timeIndices[1])), data[1]);
                Observation temperatureObservation = new Observation(phenomenonTime, TimeToString(startTime.AddMinutes(minutesPerCycle / measurementsPerCycle * timeIndices[2])), data[2]);
                Observation nitrogenObservation = new Observation(phenomenonTime, TimeToString(startTime.AddMinutes(minutesPerCycle / measurementsPerCycle * timeIndices[3])), data[3]);
                Observation phosphorusObservation = new Observation(phenomenonTime, TimeToString(startTime.AddMinutes(minutesPerCycle / measurementsPerCycle * timeIndices[4])), data[4]);


                turbidityCollection.InsertOne(turbidityObservation);
                temperatureCollection.InsertOne(temperatureObservation);
                pHCollection.InsertOne(pHObservation);
                nitrogenCollection.InsertOne(nitrogenObservation);
                phosphorusCollection.InsertOne(phosphorusObservation);
                return StatusCode(201, default(Sample));
            }
            catch (Exception e)
            {
                return StatusCode(404, e.Message);
            }
        }
        
        /// <summary>
        /// Unconvert from the conversion made by the Arduino.
        /// </summary>
        /// <param name="data"> byte values of data.</param>
        /// <returns> the data in readable numbers.</returns>
        private List<string> UnravelData(string data)
        {
            List<string> result = new List<string>();
            string turbidityByte = data.Substring(0, 2);
            string pHByte = data.Substring(2, 2);
            string temperatureByte = data.Substring(4, 2);
            string nitrogenByte = data.Substring(6, 2);
            string phosphorusByte = data.Substring(8, 2);

            result.Add(UnravelTurbidity(Convert.ToInt32(turbidityByte,16)));
            result.Add(UnravelpH(Convert.ToInt32(pHByte, 16)));
            result.Add(UnravelTemperature(Convert.ToInt32(temperatureByte, 16)));
            result.Add(UnravelNitrogen(Convert.ToInt32(nitrogenByte, 16)));
            result.Add(UnravelPhosphorus(Convert.ToInt32(phosphorusByte, 16)));

            return result;
        }

        private string UnravelpH(int b)
        {
            if (b == 254)
                return "too low";
            else if (b == 255)
                return "too high";
            else
                return (b * 4.0 / 253.0 + 5.0).ToString();
        }

        private string UnravelTurbidity(int b)
        {
            if (b == 254)
                return "too low";
            else if (b == 255)
                return "too high";
            else
                return (b * 3.0 / 253).ToString();
        }
        private string UnravelTemperature(int b)
        {
            if (b == 254)
                return "too low";
            else if (b == 255)
                return "too high";
            else
                return (b * 40.0 / 253.0 - 10).ToString();
        }

        private string UnravelPhosphorus(int b)
        {
            return b.ToString();
        }

        private string UnravelNitrogen(int b)
        {
            return b.ToString();
        }

        private List<int> UnravelTime(string data)
        {
            data = data.Substring(12, 5);
            List<int> result = new List<int>();

            for (int i = 0; i < data.Length; i++)
            {
                result.Add(Convert.ToInt32(data[i].ToString(), 16));
            }

            return result;
        }

        private string TimeToString(DateTime dateTime)
        {
            StringBuilder SB = new StringBuilder();
            SB.Append(dateTime.Year);
            SB.Append(":");
            if (dateTime.Month.ToString().Length == 1)
                SB.Append("0");
            SB.Append(dateTime.Month);
            SB.Append(":");
            if (dateTime.Day.ToString().Length == 1)
                SB.Append("0");
            SB.Append(dateTime.Day);
            SB.Append("T");
            if (dateTime.Hour.ToString().Length == 1)
                SB.Append("0");
            SB.Append(dateTime.Hour);
            SB.Append(":");
            if (dateTime.Minute.ToString().Length == 1)
                SB.Append("0");
            SB.Append(dateTime.Minute);
            SB.Append(":");
            if (dateTime.Second.ToString().Length == 1)
                SB.Append("0");
            SB.Append(dateTime.Second);
            return SB.ToString();
        }
    }
}
