version: '3.1'

services:
        mongo:
                image: sw708e19/mongo:latest
                ports: 
                  - 27017:27017
                networks:
                  - backendnet
        sensor_things_api:
                image: sw708e19/sensor_things_api:latest
                ports:
                  - 51099:80
                environment:
                  MongoDB_Host: mongo
                depends_on:
                  - mongo
                networks:
                  - backendnet
        sigfox-api:
                image: sw708e19/sigfox-api:latest
                ports: 
                  - 51100:80
                environment:
                  MongoDB_Host: mongo
                depends_on: 
                  - mongo
                networks:
                  - backendnet

networks:
        backendnet:
