# coding: utf-8

"""
    WaterProbe API

    API for waterprobing  # noqa: E501

    The version of the OpenAPI document: 1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.thing_api import ThingApi  # noqa: E501
from openapi_client.rest import ApiException


class TestThingApi(unittest.TestCase):
    """ThingApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.thing_api.ThingApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_thing(self):
        """Test case for delete_thing

        Delete an existing probe  # noqa: E501
        """
        pass

    def test_get_thing(self):
        """Test case for get_thing

        Get an existing probe  # noqa: E501
        """
        pass

    def test_get_things(self):
        """Test case for get_things

        Gets all things (probes)  # noqa: E501
        """
        pass

    def test_new_thing(self):
        """Test case for new_thing

        Creates a new probe  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
