# coding: utf-8

"""
    WaterProbe API

    API for waterprobing  # noqa: E501

    The version of the OpenAPI document: 1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.feature_of_interest_api import FeatureOfInterestApi  # noqa: E501
from openapi_client.rest import ApiException


class TestFeatureOfInterestApi(unittest.TestCase):
    """FeatureOfInterestApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.feature_of_interest_api.FeatureOfInterestApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_feature_of_interest(self):
        """Test case for delete_feature_of_interest

        deletes a FeatureOfInterest  # noqa: E501
        """
        pass

    def test_get_feature_of_interest(self):
        """Test case for get_feature_of_interest

        gets a FeatureOfInterest  # noqa: E501
        """
        pass

    def test_post_feature_of_interest(self):
        """Test case for post_feature_of_interest

        posting a new FeatureOfInterest  # noqa: E501
        """
        pass

    def test_put_feature_of_interest(self):
        """Test case for put_feature_of_interest

        updates a FeatureOfInterest  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
