# coding: utf-8

"""
    WaterProbe API

    API for waterprobing  # noqa: E501

    The version of the OpenAPI document: 1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.models.tm_instant import TmInstant  # noqa: E501
from openapi_client.rest import ApiException


class TestTmInstant(unittest.TestCase):
    """TmInstant unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTmInstant(self):
        """Test TmInstant"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openapi_client.models.tm_instant.TmInstant()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
