# coding: utf-8

"""
    WaterProbe API

    API for waterprobing  # noqa: E501

    The version of the OpenAPI document: 1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.datastream_api import DatastreamApi  # noqa: E501
from openapi_client.rest import ApiException


class TestDatastreamApi(unittest.TestCase):
    """DatastreamApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.datastream_api.DatastreamApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_datastream(self):
        """Test case for delete_datastream

        deletes a datastream  # noqa: E501
        """
        pass

    def test_get_datastream(self):
        """Test case for get_datastream

        Gets a datastream  # noqa: E501
        """
        pass

    def test_get_datastreams(self):
        """Test case for get_datastreams

        Get all datastreams from thing  # noqa: E501
        """
        pass

    def test_post_datastream(self):
        """Test case for post_datastream

        posts a datastream  # noqa: E501
        """
        pass

    def test_put_datastream(self):
        """Test case for put_datastream

        put to a datastream  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
