# coding: utf-8

"""
    WaterProbe API

    API for waterprobing  # noqa: E501

    The version of the OpenAPI document: 1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.location_api import LocationApi  # noqa: E501
from openapi_client.rest import ApiException


class TestLocationApi(unittest.TestCase):
    """LocationApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.location_api.LocationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_location(self):
        """Test case for delete_location

        deletes a sensor  # noqa: E501
        """
        pass

    def test_get_location(self):
        """Test case for get_location

        gets a location  # noqa: E501
        """
        pass

    def test_postlocation(self):
        """Test case for postlocation

        posting a new location  # noqa: E501
        """
        pass

    def test_put_location(self):
        """Test case for put_location

        updates a location  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
