# coding: utf-8

"""
    WaterProbe API

    API for waterprobing  # noqa: E501

    The version of the OpenAPI document: 1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class Location(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'description': 'str',
        'encoding_type': 'object',
        'location': 'object'
    }

    attribute_map = {
        'description': 'description',
        'encoding_type': 'encodingType',
        'location': 'location'
    }

    def __init__(self, description=None, encoding_type=None, location=None):  # noqa: E501
        """Location - a model defined in OpenAPI"""  # noqa: E501

        self._description = None
        self._encoding_type = None
        self._location = None
        self.discriminator = None

        self.description = description
        self.encoding_type = encoding_type
        self.location = location

    @property
    def description(self):
        """Gets the description of this Location.  # noqa: E501


        :return: The description of this Location.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this Location.


        :param description: The description of this Location.  # noqa: E501
        :type: str
        """
        if description is None:
            raise ValueError("Invalid value for `description`, must not be `None`")  # noqa: E501

        self._description = description

    @property
    def encoding_type(self):
        """Gets the encoding_type of this Location.  # noqa: E501


        :return: The encoding_type of this Location.  # noqa: E501
        :rtype: object
        """
        return self._encoding_type

    @encoding_type.setter
    def encoding_type(self, encoding_type):
        """Sets the encoding_type of this Location.


        :param encoding_type: The encoding_type of this Location.  # noqa: E501
        :type: object
        """
        if encoding_type is None:
            raise ValueError("Invalid value for `encoding_type`, must not be `None`")  # noqa: E501

        self._encoding_type = encoding_type

    @property
    def location(self):
        """Gets the location of this Location.  # noqa: E501


        :return: The location of this Location.  # noqa: E501
        :rtype: object
        """
        return self._location

    @location.setter
    def location(self, location):
        """Sets the location of this Location.


        :param location: The location of this Location.  # noqa: E501
        :type: object
        """
        if location is None:
            raise ValueError("Invalid value for `location`, must not be `None`")  # noqa: E501

        self._location = location

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Location):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
