# coding: utf-8

"""
    WaterProbe API

    API for waterprobing  # noqa: E501

    The version of the OpenAPI document: 1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.sensor_api import SensorApi  # noqa: E501
from openapi_client.rest import ApiException


class TestSensorApi(unittest.TestCase):
    """SensorApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.sensor_api.SensorApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_sensor(self):
        """Test case for delete_sensor

        deletes a sensor  # noqa: E501
        """
        pass

    def test_get_sensor(self):
        """Test case for get_sensor

        gets a sensor  # noqa: E501
        """
        pass

    def test_post_sensor(self):
        """Test case for post_sensor

        post a sensor  # noqa: E501
        """
        pass

    def test_put_sensor(self):
        """Test case for put_sensor

        puts a sensor  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
