version: '3.1'

services:
  mongo:
    build:
      context: .
      dockerfile: Dockerfile-custommongo
    restart: always
    ports:
      - 27017:27017


  sensor_things_api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 51099:80
    environment:
      MongoDB__Host: mongo
    depends_on:
      - mongo
