/*
 * WaterProbe API
 *
 * API for waterprobing
 *
 * The version of the OpenAPI document: 1
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using SensorThingsAPI.Attributes;
using Microsoft.AspNetCore.Authorization;
using SensorThingsAPI.Models;
using SensorThingsAPI.Services;

namespace SensorThingsAPI.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class ObservationApiController : ControllerBase
    {

        private readonly ObservationService _observationService;
        public ObservationApiController(ObservationService observationService)
        {
            _observationService = observationService;
        }


        /// <summary>
        /// Call to get observation from database
        /// </summary>
        /// <param name="observationName">Unique observationName</param>
        /// <response code="201">Successful response</response>
        /// <response code="404">Not created response</response>
        [HttpGet]
        [Route("/Observation")]
        [ValidateModelState]
        [SwaggerOperation("GetObservation")]
        [SwaggerResponse(statusCode: 201, type: typeof(Sample), description: "Successful response")]
        [SwaggerResponse(statusCode: 404, type: typeof(string), description: "Not created response")]
        public virtual IActionResult GetObservation([FromQuery]string observationName)
        { 

            //TODO: Uncomment the next line to return response 201 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(201, default(Sample));
            //TODO: Uncomment the next line to return response 404 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(404, default(string));
            string exampleJson = null;
            exampleJson = "{\r\n  \"placeholder\" : \"placeholder\"\r\n}";
            
            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<Sample>(exampleJson)
            : default(Sample);
            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// Get all observations associated to datastream
        /// </summary>
        /// <param name="datastreamRef">Ref to unique datastream</param>
        /// <response code="201">Successful response</response>
        /// <response code="404">Not created response</response>
        [HttpGet]
        [Route("/Observations")]
        [ValidateModelState]
        [SwaggerOperation("GetObservations")]
        [SwaggerResponse(statusCode: 201, type: typeof(Sample), description: "Successful response")]
        [SwaggerResponse(statusCode: 404, type: typeof(string), description: "Not created response")]
        public virtual IActionResult GetObservations([FromQuery]string datastreamRef)
        {
            try
            {
                var observations = _observationService.GetDatastreamsObservations(datastreamRef);

                string json = JsonConvert.SerializeObject(observations, Formatting.Indented, new JsonSerializerSettings()
                {

                    NullValueHandling = NullValueHandling.Include });


                return StatusCode(200, json);
            }
            catch (Exception e)
            {
                return StatusCode(404, e.Message);
            }
        }

        /// <summary>
        /// Call to write observation to database
        /// </summary>
        /// <param name="observation">Optional properties represented as json for the Thing</param>
        /// <response code="201">Successful response</response>
        /// <response code="404">Not created response</response>
        [HttpPost]
        [Route("/Observation")]
        [ValidateModelState]
        [SwaggerOperation("PostObservation")]
        [SwaggerResponse(statusCode: 201, type: typeof(Sample), description: "Successful response")]
        [SwaggerResponse(statusCode: 404, type: typeof(string), description: "Not created response")]
        public virtual IActionResult PostObservation([FromBody]Observation observation)
        { 

            //TODO: Uncomment the next line to return response 201 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(201, default(Sample));
            //TODO: Uncomment the next line to return response 404 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(404, default(string));
            string exampleJson = null;
            exampleJson = "{\r\n  \"placeholder\" : \"placeholder\"\r\n}";
            
            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<Sample>(exampleJson)
            : default(Sample);
            //TODO: Change the data returned
            return new ObjectResult(example);
        }
    }
}
